name: PSR-12 coding standard, Test, Coverage
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  coding-standard:
    name: PSR-12 coding standard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: Install PHP code sniffer
        run: composer global require squizlabs/php_codesniffer
      - name: Check against PSR12 standard
        run: |
          `composer global config bin-dir --absolute --quiet`/phpcs --standard=PSR12 ./src

  tests:
    needs: coding-standard
    name: "OS: ${{ matrix.os }} | PHP: ${{ matrix.php }} | Laravel: ${{ matrix.laravel }} | BP-CRUD: ${{ matrix.backpack }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.0, 8.1 ]
        laravel: [ 8, 9 ]
        backpack: [ 5 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        run: |
          composer require laravel/framework:^${{ matrix.laravel }} backpack/crud:^${{ matrix.backpack }} --no-interaction --prefer-dist
      - name: Install Backpack Pro
        env:
          USERNAME: ${{ secrets.BACKPACK_AUTH_USERNAME }}
        if: "${{ env.USERNAME != '' }}"
        run: |
          composer config http-basic.backpackforlaravel.com $BACKPACK_AUTH_USERNAME $BACKPACK_AUTH_PASSWORD --no-ansi --no-interaction
          composer require backpack/pro ^1.0 --no-interaction --prefer-dist
      - name: Run tests
        run: ./vendor/bin/phpunit --testdox --verbose

  coverage:
    needs: tests
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          php-version: 8.1
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Run tests for coverage
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml
      - name: Push to Codecov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
